name: Update Components Info

on:
  watch:
    types: started
  schedule:
    - cron: '0 * * * *'

jobs:
  update-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
      
      - name: Update components info
        run: npx esno ./scripts/update-components.ts
      
      - name: Commit
        run: |-
          git config --global user.email "997909544@qq.com" && git config --global user.name "xbmlz"
          git diff
          git add . && git commit -m ":memo: Update components info" || exit 0

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
